/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.Componetes.CampoDeTestoFocusListaner;
import controller.ProjetoController;
import controller.UsuarioController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Map;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import view.Componetes.MeuScrollbarUI;

/**
 *
 * @author matheus
 */
public class Janela extends javax.swing.JFrame {

    private Painel painelAtivo;
    
    /**
     * Creates new form Janela1
     */
    public Janela() {
        initComponents();
        iniciarListaners();
        nome.setText(UsuarioController.getNomeUsuarioLogado());
        cargo.setText(UsuarioController.getCargoUsuarioLogado());
        btnNovo.setVisible(false);
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);
        btnLimpar.setVisible(false);
        campoDeBuscaContainer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelOpcoesDeNavegacao = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnMenuEscondido = new javax.swing.JButton();
        campoDeBuscaContainer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        campoDeBuscaBorder = new javax.swing.JPanel();
        campoDeBusca = new javax.swing.JTextField();
        navegacaoLateral = new javax.swing.JPanel();
        usuarioLogado = new javax.swing.JPanel();
        imgPerfil = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        btnNavUsuarios = new javax.swing.JButton();
        btnNavProjetos = new javax.swing.JButton();
        btnNavCasosDeTeste = new javax.swing.JButton();
        BtnNavRoteiroDeTeste = new javax.swing.JButton();
        BtnNavCasosDeUso = new javax.swing.JButton();
        conteudoContainer = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PBTest1.1");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        painelOpcoesDeNavegacao.setBackground(new java.awt.Color(51, 51, 51));
        painelOpcoesDeNavegacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelOpcoesDeNavegacao.setPreferredSize(new java.awt.Dimension(0, 60));

        btnNovo.setBackground(new java.awt.Color(102, 102, 102));
        btnNovo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(204, 204, 204));
        btnNovo.setText("Novo");
        btnNovo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnNovo.setFocusCycleRoot(true);
        btnNovo.setFocusPainted(false);
        btnNovo.setRequestFocusEnabled(false);
        btnNovo.setSelected(true);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(102, 102, 102));
        btnSalvar.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(204, 204, 204));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnSalvar.setFocusPainted(false);
        btnSalvar.setRequestFocusEnabled(false);
        btnSalvar.setSelected(true);

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setRequestFocusEnabled(false);
        btnCancelar.setSelected(true);

        btnLimpar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpar.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(204, 204, 204));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnLimpar.setFocusPainted(false);
        btnLimpar.setRequestFocusEnabled(false);
        btnLimpar.setSelected(true);

        btnMenuEscondido.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuEscondido.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnMenuEscondido.setForeground(new java.awt.Color(51, 51, 51));
        btnMenuEscondido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones/icons8-menu.png"))); // NOI18N
        btnMenuEscondido.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnMenuEscondido.setFocusPainted(false);
        btnMenuEscondido.setFocusable(false);
        btnMenuEscondido.setPreferredSize(new java.awt.Dimension(37, 37));
        btnMenuEscondido.setRequestFocusEnabled(false);
        btnMenuEscondido.setSelected(true);

        campoDeBuscaContainer.setBackground(new java.awt.Color(51, 51, 51));
        campoDeBuscaContainer.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones/icons8-search.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);

        campoDeBuscaBorder.setBackground(new java.awt.Color(102, 102, 102));
        campoDeBuscaBorder.setFocusable(false);
        campoDeBuscaBorder.setPreferredSize(new java.awt.Dimension(300, 2));
        campoDeBuscaBorder.setRequestFocusEnabled(false);

        javax.swing.GroupLayout campoDeBuscaBorderLayout = new javax.swing.GroupLayout(campoDeBuscaBorder);
        campoDeBuscaBorder.setLayout(campoDeBuscaBorderLayout);
        campoDeBuscaBorderLayout.setHorizontalGroup(
            campoDeBuscaBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        campoDeBuscaBorderLayout.setVerticalGroup(
            campoDeBuscaBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        campoDeBusca.setBackground(new java.awt.Color(51, 51, 51));
        campoDeBusca.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        campoDeBusca.setForeground(new java.awt.Color(255, 255, 255));
        campoDeBusca.setBorder(null);
        campoDeBusca.setCaretColor(new java.awt.Color(255, 255, 255));
        campoDeBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout campoDeBuscaContainerLayout = new javax.swing.GroupLayout(campoDeBuscaContainer);
        campoDeBuscaContainer.setLayout(campoDeBuscaContainerLayout);
        campoDeBuscaContainerLayout.setHorizontalGroup(
            campoDeBuscaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoDeBuscaContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(campoDeBuscaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoDeBuscaBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        campoDeBuscaContainerLayout.setVerticalGroup(
            campoDeBuscaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campoDeBuscaContainerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(campoDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(campoDeBuscaBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelOpcoesDeNavegacaoLayout = new javax.swing.GroupLayout(painelOpcoesDeNavegacao);
        painelOpcoesDeNavegacao.setLayout(painelOpcoesDeNavegacaoLayout);
        painelOpcoesDeNavegacaoLayout.setHorizontalGroup(
            painelOpcoesDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesDeNavegacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuEscondido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDeBuscaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelOpcoesDeNavegacaoLayout.setVerticalGroup(
            painelOpcoesDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesDeNavegacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoDeBuscaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(painelOpcoesDeNavegacaoLayout.createSequentialGroup()
                .addGroup(painelOpcoesDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelOpcoesDeNavegacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMenuEscondido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelOpcoesDeNavegacaoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelOpcoesDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnSalvar)
                            .addComponent(btnCancelar)
                            .addComponent(btnLimpar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campoDeBuscaContainer.getAccessibleContext().setAccessibleName("");

        navegacaoLateral.setBackground(new java.awt.Color(102, 102, 102));
        navegacaoLateral.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        usuarioLogado.setBackground(new java.awt.Color(0, 204, 102));
        usuarioLogado.setPreferredSize(new java.awt.Dimension(1, 146));

        imgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones/imgPerfilGenerico.jpg"))); // NOI18N

        nome.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome.setText("jLabel2");

        cargo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cargo.setForeground(new java.awt.Color(255, 255, 255));
        cargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cargo.setText("jLabel3");

        javax.swing.GroupLayout usuarioLogadoLayout = new javax.swing.GroupLayout(usuarioLogado);
        usuarioLogado.setLayout(usuarioLogadoLayout);
        usuarioLogadoLayout.setHorizontalGroup(
            usuarioLogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLogadoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(usuarioLogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuarioLogadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addComponent(imgPerfil, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
            .addComponent(cargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        usuarioLogadoLayout.setVerticalGroup(
            usuarioLogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLogadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargo)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnNavUsuarios.setBackground(new java.awt.Color(102, 102, 102));
        btnNavUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnNavUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        btnNavUsuarios.setText("Usuarios");
        btnNavUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnNavUsuarios.setFocusPainted(false);
        btnNavUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavUsuarios.setOpaque(false);

        btnNavProjetos.setBackground(new java.awt.Color(102, 102, 102));
        btnNavProjetos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnNavProjetos.setForeground(new java.awt.Color(204, 204, 204));
        btnNavProjetos.setText("Projetos");
        btnNavProjetos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnNavProjetos.setFocusPainted(false);
        btnNavProjetos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavProjetos.setOpaque(false);

        btnNavCasosDeTeste.setBackground(new java.awt.Color(102, 102, 102));
        btnNavCasosDeTeste.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnNavCasosDeTeste.setForeground(new java.awt.Color(204, 204, 204));
        btnNavCasosDeTeste.setText("Casos de teste");
        btnNavCasosDeTeste.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnNavCasosDeTeste.setFocusPainted(false);
        btnNavCasosDeTeste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavCasosDeTeste.setOpaque(false);

        BtnNavRoteiroDeTeste.setBackground(new java.awt.Color(102, 102, 102));
        BtnNavRoteiroDeTeste.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BtnNavRoteiroDeTeste.setForeground(new java.awt.Color(204, 204, 204));
        BtnNavRoteiroDeTeste.setText("Roteiros de teste");
        BtnNavRoteiroDeTeste.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        BtnNavRoteiroDeTeste.setFocusPainted(false);
        BtnNavRoteiroDeTeste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnNavRoteiroDeTeste.setOpaque(false);

        BtnNavCasosDeUso.setBackground(new java.awt.Color(102, 102, 102));
        BtnNavCasosDeUso.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BtnNavCasosDeUso.setForeground(new java.awt.Color(204, 204, 204));
        BtnNavCasosDeUso.setText("Casos de uso");
        BtnNavCasosDeUso.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        BtnNavCasosDeUso.setFocusPainted(false);
        BtnNavCasosDeUso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnNavCasosDeUso.setOpaque(false);

        javax.swing.GroupLayout navegacaoLateralLayout = new javax.swing.GroupLayout(navegacaoLateral);
        navegacaoLateral.setLayout(navegacaoLateralLayout);
        navegacaoLateralLayout.setHorizontalGroup(
            navegacaoLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(btnNavUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNavProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNavCasosDeTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnNavRoteiroDeTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnNavCasosDeUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navegacaoLateralLayout.setVerticalGroup(
            navegacaoLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegacaoLateralLayout.createSequentialGroup()
                .addComponent(usuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnNavUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNavProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnNavCasosDeUso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNavCasosDeTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnNavRoteiroDeTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        conteudoContainer.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOpcoesDeNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navegacaoLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteudoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelOpcoesDeNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navegacaoLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conteudoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        conteudoContainer.getHorizontalScrollBar().setUI(new MeuScrollbarUI());
        conteudoContainer.getVerticalScrollBar().setUI(new MeuScrollbarUI());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNavCasosDeUso;
    private javax.swing.JButton BtnNavRoteiroDeTeste;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenuEscondido;
    private javax.swing.JButton btnNavCasosDeTeste;
    private javax.swing.JButton btnNavProjetos;
    private javax.swing.JButton btnNavUsuarios;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField campoDeBusca;
    private javax.swing.JPanel campoDeBuscaBorder;
    private javax.swing.JPanel campoDeBuscaContainer;
    private javax.swing.JLabel cargo;
    private javax.swing.JScrollPane conteudoContainer;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel navegacaoLateral;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel painelOpcoesDeNavegacao;
    private javax.swing.JPanel usuarioLogado;
    // End of variables declaration//GEN-END:variables


    private void iniciarListaners(){
        BtnNavRoteiroDeTeste.addMouseListener(new BotoesDeNavegacaolistaner((e) -> {
        }, BtnNavRoteiroDeTeste));
        BtnNavCasosDeUso.addMouseListener(new BotoesDeNavegacaolistaner((e) -> {
        }, BtnNavCasosDeUso));
        btnNavCasosDeTeste.addMouseListener(new BotoesDeNavegacaolistaner((e) -> {
        }, btnNavCasosDeTeste));
        btnNavUsuarios.addMouseListener(new BotoesDeNavegacaolistaner((e) -> {
        }, btnNavUsuarios));
        btnNavProjetos.addMouseListener(new BotoesDeNavegacaolistaner((e) -> {
        }, btnNavProjetos));
        
        btnNovo.addMouseListener(new BotoesDeNavegacaolistaner((e) -> {
            painelAtivo.btnNovoOnClick(e);
        }, btnNovo));
        btnSalvar.addMouseListener(new BotoesContextolistaner((e) -> {
            painelAtivo.btnSalvarOnClick(e);
        }, btnSalvar));
        btnCancelar.addMouseListener(new BotoesContextolistaner((e) -> {
            painelAtivo.btnCancelarOnClick(e);
        }, btnCancelar));
        btnMenuEscondido.addMouseListener(new BotoesContextolistaner((e) -> {
            int width = 170;
            if (navegacaoLateral.getWidth() != width){
                new Thread(()->{
                    for (int i = 1; i <= width; i++){
                        navegacaoLateral.setSize(new Dimension(i, navegacaoLateral.getHeight()));
                        Janela.this.repaint();
                        try {
                            Thread.sleep(1);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }).start();
            } else {
                new Thread(()->{
                    for (int i = width; i >= 0; i--){
                        navegacaoLateral.setSize(new Dimension(i, navegacaoLateral.getHeight()));
                        Janela.this.repaint();
                        try {
                            Thread.sleep(1);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }).start();

            }
        }, btnMenuEscondido));
        
        
        btnLimpar.addMouseListener(new BotoesContextolistaner((e) -> {
            painelAtivo.btnLimparOnClick(e);
        }, btnLimpar));
        
        campoDeBusca.addFocusListener(new CampoDeTestoFocusListaner(Color.white, campoDeBuscaBorder));
        
        btnNavUsuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                trocarDePainel(Paineis.USUARIOS, null);
            }
            
        });
        
        
        btnNavProjetos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                trocarDePainel(Paineis.PROJETOS, null);
            }
        });
        
        BtnNavCasosDeUso.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                trocarDePainel(Paineis.CASOS_DE_USO, null);
            }
        });
        
        btnNavCasosDeTeste.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                trocarDePainel(Paineis.CASOS_DE_TESTE, null);
            }
        });
        
        BtnNavRoteiroDeTeste.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                trocarDePainel(Paineis.ROTEIROS_DE_TESTE, null);
            }
        });
       
         
    }
    
    private void configurarBotoesDeContexto(){
        switch (painelAtivo.pegarTipoDePainel()){
            case LISTAGEM:
                btnNovo.setVisible(true);
                btnSalvar.setVisible(false);
                btnCancelar.setVisible(false);
                btnLimpar.setVisible(false);
                campoDeBuscaContainer.setVisible(false);
                break;
            case FORMULARIO_DE_CRIACAO:
                btnNovo.setVisible(false);
                btnSalvar.setVisible(true);
                btnCancelar.setVisible(true);
                btnLimpar.setVisible(true);
                campoDeBuscaContainer.setVisible(false);
                break;
            case FORMULARIO_DE_EDICAO:
                btnNovo.setVisible(false);
                btnSalvar.setVisible(true);
                btnCancelar.setVisible(true);
                btnLimpar.setVisible(false);
                campoDeBuscaContainer.setVisible(false);
                break;
            case NULO:
                btnNovo.setVisible(false);
                btnSalvar.setVisible(false);
                btnCancelar.setVisible(false);
                btnLimpar.setVisible(false);
                campoDeBuscaContainer.setVisible(false);
                break;
            default:
                throw new AssertionError(painelAtivo.pegarTipoDePainel().name());
            
        }
    }
    
    private class BotoesDeNavegacaolistaner implements MouseListener {
        
        private Consumer<MouseEvent> onClick;
        private JButton content;
        public BotoesDeNavegacaolistaner(Consumer<MouseEvent> onClick, JButton btn) {
            this.onClick = onClick;
            content = btn;
        }
        @Override
        public void mouseClicked(MouseEvent e) {
            onClick.accept(e);   
        }
        @Override
        public void mousePressed(MouseEvent e) {
        }
        @Override
        public void mouseReleased(MouseEvent e) {
            content.setBackground(new java.awt.Color(204, 204, 204));
        }
        @Override
        public void mouseEntered(MouseEvent e) {
            content.setForeground(Color.white);
        }
        @Override
        public void mouseExited(MouseEvent e) {
            content.setBackground(new java.awt.Color(102, 102, 102));
            content.setForeground(new java.awt.Color(204, 204, 204));
        }
    }

    private class BotoesContextolistaner implements MouseListener {
        
        private Consumer<MouseEvent> onClick;
        private final JButton content;
        public BotoesContextolistaner(Consumer<MouseEvent> onClick, JButton btn) {
            this.onClick = onClick;
            content = btn;
        }
        @Override
        public void mouseClicked(MouseEvent e) {
            onClick.accept(e);   
        }
        @Override
        public void mousePressed(MouseEvent e) {
        }
        @Override
        public void mouseReleased(MouseEvent e) {
            content.setBackground(new java.awt.Color(204, 204, 204));
        }
        @Override
        public void mouseEntered(MouseEvent e) {
            content.setForeground(Color.white);
        }
        @Override
        public void mouseExited(MouseEvent e) {
            content.setBackground(new java.awt.Color(102, 102, 102));
            content.setForeground(new java.awt.Color(204, 204, 204));
        }
    }
    
    public void trocarDePainel(Paineis p, Map<?, ?> dados){
        switch(p){
            case USUARIOS:
                trocarDePainel(mainApp.PaineisDeTRabalho.USUARIOS);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case FORMULARIO_DE_CADASTRO_DE_USUARIO:
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case PROJETOS:
                trocarDePainel(mainApp.PaineisDeTRabalho.PROJETOS);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case FORMULARIO_DE_CADASTRO_DE_PROJETO:
                trocarDePainel(mainApp.PaineisDeTRabalho.FORMULARIO_DE_CADASTRO_DE_PROJETO);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case CASOS_DE_USO:
                if (!ProjetoController.temProjetoAtivo()){
                    JOptionPane.showMessageDialog(this, "Ative um Projeto!");
                } else {
                    trocarDePainel(mainApp.PaineisDeTRabalho.CASOS_DE_USO);
                    painelAtivo.setData(dados);
                    painelAtivo.preProcessamentoAntesDeAbrir();
                    configurarBotoesDeContexto();
               }
                break;
            case FORMULARIO_DE_CADASTRO_DE_CASOS_DE_USO:
                trocarDePainel(mainApp.PaineisDeTRabalho.FORMULARIO_DE_CADASTRO_DE_CASO_DE_USO);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();

                break;
            case CASOS_DE_TESTE:
                if (!ProjetoController.temProjetoAtivo()){
                    JOptionPane.showMessageDialog(this, "Ative um Projeto!");
                } else {
                    trocarDePainel(mainApp.PaineisDeTRabalho.CASOS_DE_TESTE);
                    painelAtivo.setData(dados);
                    painelAtivo.preProcessamentoAntesDeAbrir();
                    configurarBotoesDeContexto();
                }
                break;
            case FORMULARIO_DE_CADASTRO_DE_CASOS_DE_TESTE:
                trocarDePainel(mainApp.PaineisDeTRabalho.FORMULARIO_DE_CADASTRO_DE_CASOS_DE_TESTE);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case ROTEIROS_DE_TESTE:
                if (!ProjetoController.temProjetoAtivo()){
                    JOptionPane.showMessageDialog(this, "Ative um Projeto!");
                } else {
                    trocarDePainel(mainApp.PaineisDeTRabalho.ROTEIROS_DE_TESTE);
                    painelAtivo.setData(dados);
                    painelAtivo.preProcessamentoAntesDeAbrir();
                     configurarBotoesDeContexto();
                }
                break;
            case FORMULARIO_DE_CADASTRO_DE_ROTEIROS_DE_TESTE:
                trocarDePainel(mainApp.PaineisDeTRabalho.FORMULARIO_DE_CADASTRO_DE_ROTEIROS_DE_TESTE);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case EXECUCAO_DE_ROTEIRO: 
                trocarDePainel(mainApp.PaineisDeTRabalho.EXECUCAO_DE_ROTEIRO);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
            case MATRIZ:
                trocarDePainel(mainApp.PaineisDeTRabalho.MATRIZ);
                painelAtivo.setData(dados);
                painelAtivo.preProcessamentoAntesDeAbrir();
                configurarBotoesDeContexto();
                break;
        }
    }
    
    private void trocarDePainel(Painel p){
        if (painelAtivo != null){
            painelAtivo.preProcessamentoAntesDeFechar();
            conteudoContainer.remove(painelAtivo.getCompomenteRaiz());    
        }
        painelAtivo = p;
        conteudoContainer.setViewportView(p.getCompomenteRaiz());
        this.revalidate();
        this.repaint();
    }

    
}

