/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cards;

import controller.CasoDeTesteController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import javax.swing.JOptionPane;
import model.CasoDeTeste;
import view.Paineis;
import view.mainApp;

/**
 *
 * @author matheus
 */
public class CasoDeTesteCard extends javax.swing.JPanel {
    
    private CasoDeTeste casoDeTeste;
    /**
     * Creates new form ProjetoCard
     */
    public CasoDeTesteCard(CasoDeTeste c) {
        initComponents();
        casoDeTeste = c;
        nome.setText(c.getNome());
        codigo.setText(c.getCodigo());
        classe.setText(c.getSrcCasoDeTeste());
        email.setText(c.getEmailUsuario());
        iniciarListaners();
    }
    
    private void iniciarListaners(){
        btnVerEditar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HashMap<String, Object> hashMap = new HashMap<>();
                hashMap.put("caso de teste", casoDeTeste);
                hashMap.put("artefato", casoDeTeste.getArtefatoDeTeste());
                mainApp.trocarDePainel(Paineis.FORMULARIO_DE_CADASTRO_DE_CASOS_DE_TESTE, hashMap);
            }
        });
        
        btnDeletar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int i = JOptionPane.showConfirmDialog(null, "Você está certo disso?", "tem certeza?", JOptionPane.YES_NO_OPTION);
                if (i == 0){
                    CasoDeTesteController.deletarCasoDeTeste(casoDeTeste);
                    HashMap<String, Object> hashMap = new HashMap<>();
                    hashMap.put("artefato", casoDeTeste.getArtefatoDeTeste());
                    hashMap.put("atualizar", "sim");
                    mainApp.trocarDePainel(Paineis.CASOS_DE_TESTE, hashMap);
                }                
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        classe = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        btnVerEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);

        nome.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nome.setText("nome");
        nome.setToolTipText("nome do caso de teste");
        nome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        codigo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        codigo.setText("codigo");
        codigo.setToolTipText("codigo do caso de teste");
        codigo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        classe.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        classe.setForeground(new java.awt.Color(102, 102, 102));
        classe.setText("crrr");
        classe.setToolTipText("classe de teste");
        classe.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        email.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("e-mail");
        email.setToolTipText("e-mail do usuario que criou este caso de teste");
        email.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnVerEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnVerEditar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnVerEditar.setForeground(new java.awt.Color(153, 153, 153));
        btnVerEditar.setText("ver/editar");
        btnVerEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnVerEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEditar.setFocusPainted(false);
        btnVerEditar.setFocusable(false);
        btnVerEditar.setOpaque(false);

        btnDeletar.setBackground(new java.awt.Color(0, 0, 0));
        btnDeletar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(153, 153, 153));
        btnDeletar.setText("deletar");
        btnDeletar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setFocusPainted(false);
        btnDeletar.setFocusable(false);
        btnDeletar.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnVerEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email)))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnVerEditar;
    private javax.swing.JLabel classe;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
