/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.cards.CasoDeUsoCard;
import controller.CasoDeUsoController;
import controller.CasoDeUsoController;
import controller.UsuarioController;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.util.Map;
import model.CasoDeUso;
import model.Usuario;
import resources.Cores;

/**
 *
 * @author matheus
 */
public class CasosDeUsoPainel extends javax.swing.JPanel implements Painel{

    private TipoDePainel tipo = TipoDePainel.LISTAGEM;
    private int quantidadeDeLinhas = 1;
    private GridLayout layout;
    /**
     * Creates new form UsuariosPainel1
     */
    public CasosDeUsoPainel() {
        initComponents();
        layout = (GridLayout) this.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridLayout(4, 1, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    private void carregarCasosdeUsoNaLista () {
        CasoDeUsoController.getListaDeCasosDeUso().forEach(u -> {
            addItemNaLista(novoCard(u));
        });
        
    }
    
    private CasoDeUsoCard novoCard(CasoDeUso u){
        return new CasoDeUsoCard(u);
    }
    
    private void addItemNaLista(CasoDeUsoCard card){
        layout.setRows(quantidadeDeLinhas++);   
        super.add(card);
        super.revalidate();
    }

    @Override
    public void preProcessamentoAntesDeAbrir() {
        super.removeAll();
        quantidadeDeLinhas = 1;
        carregarCasosdeUsoNaLista();
    }

    @Override
    public void preProcessamentoAntesDeFechar() {
    }

    @Override
    public Component getCompomenteRaiz() {
        return this;
    }

    @Override
    public void btnNovoOnClick(MouseEvent e) {
        mainApp.trocarDePainel(Paineis.FORMULARIO_DE_CADASTRO_DE_CASOS_DE_USO, null);
    }

    @Override
    public void btnSalvarOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void btnCancelarOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void btnLimparOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setData(Map<?, ?> dados) {
    }

    
    @Override
    public TipoDePainel pegarTipoDePainel() {
        return tipo;
    }
}
