/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.cards.UsuarioCard;
import controller.UsuarioController;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.util.Map;
import model.Usuario;

/**
 *
 * @author matheus
 */
public class UsuariosPainel extends javax.swing.JPanel implements Painel{

    private TipoDePainel tipo = TipoDePainel.LISTAGEM;
    private int quantidadeDeLinhas = 1;
    private GridLayout layout;
    /**
     * Creates new form UsuariosPainel1
     */
    public UsuariosPainel() {
        initComponents();
        layout = (GridLayout) this.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridLayout(1, 1, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    private void carregarUsuarioNaLista () {

        UsuarioController.getListaDeUsuarios().forEach(u -> {
            addItemNaLista(novoCard(u));
        });
    }
    
    private UsuarioCard novoCard(Usuario u){
        return new UsuarioCard(u.getNome(), u.getEmail(), u.getCargo());
    }
    
    private void addItemNaLista(UsuarioCard card){
        layout.setRows(quantidadeDeLinhas++);
        super.add(card);
        super.revalidate();
    }

    @Override
    public void preProcessamentoAntesDeAbrir() {
        super.removeAll();
        carregarUsuarioNaLista();
    }

    @Override
    public void preProcessamentoAntesDeFechar() {
    }

    @Override
    public Component getCompomenteRaiz() {
        return this;
    }


    @Override
    public void btnNovoOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void btnSalvarOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void btnCancelarOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void btnLimparOnClick(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setData(Map<?, ?> dados) {
    }

    @Override
    public TipoDePainel pegarTipoDePainel() {
        return tipo;
    }

}
