/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cards;

import controller.CasoDeUsoController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import javax.swing.JOptionPane;
import model.CasoDeUso;
import view.Paineis;
import view.mainApp;

/**
 *
 * @author matheus
 */
public class CasoDeUsoCard extends javax.swing.JPanel {
    
    private CasoDeUso casoDeUso;
    /**
     * Creates new form ProjetoCard
     */
    public CasoDeUsoCard(CasoDeUso c) {
        initComponents();
        casoDeUso = c;
        nome.setText(c.getNome());
        codigo.setText(c.getCodigo());
        objetivo.setText(c.getObjetivo());
        atores.setText(c.getAtores());
        email.setText(c.getEmailUsuario());
        iniciarListaners();
    }
    
    private void iniciarListaners(){
        btnVerEditar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HashMap<String, CasoDeUso> hashMap = new HashMap<String, CasoDeUso>();
                hashMap.put("caso de uso", casoDeUso);
                mainApp.trocarDePainel(Paineis.FORMULARIO_DE_CADASTRO_DE_CASOS_DE_USO, hashMap);
            }
        });
        
        btnDeletar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int i = JOptionPane.showConfirmDialog(null, "Você está certo disso?", "tem certeza?", JOptionPane.YES_NO_OPTION);
                if (i == 0){
                    CasoDeUsoController.deletarCasoDeUsoDeCodigo(casoDeUso.getCodigo());
                    mainApp.trocarDePainel(Paineis.CASOS_DE_USO, null);
                }                
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        objetivo = new javax.swing.JLabel();
        atores = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        btnVerEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        setMaximumSize(getMinimumSize());
        setMinimumSize(new java.awt.Dimension(90, 135));

        nome.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nome.setText("nome");
        nome.setToolTipText("nome do caso de uso");
        nome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        codigo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        codigo.setText("codigo");
        codigo.setToolTipText("codigo do caso de uso");
        codigo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        objetivo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        objetivo.setForeground(new java.awt.Color(102, 102, 102));
        objetivo.setText("objetivo");
        objetivo.setToolTipText("objetivo do caso de uso");
        objetivo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        atores.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        atores.setForeground(new java.awt.Color(102, 102, 102));
        atores.setText("atores");
        atores.setToolTipText("atores deste caso de uso");
        atores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        email.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("e-mail");
        email.setToolTipText("e-mail do usuario que criou este caso de uso");
        email.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnVerEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnVerEditar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnVerEditar.setForeground(new java.awt.Color(153, 153, 153));
        btnVerEditar.setText("ver/editar");
        btnVerEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnVerEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEditar.setFocusPainted(false);
        btnVerEditar.setFocusable(false);
        btnVerEditar.setOpaque(false);

        btnDeletar.setBackground(new java.awt.Color(0, 0, 0));
        btnDeletar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(153, 153, 153));
        btnDeletar.setText("deletar");
        btnDeletar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setFocusPainted(false);
        btnDeletar.setFocusable(false);
        btnDeletar.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(objetivo, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(objetivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atores))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atores;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnVerEditar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel objetivo;
    // End of variables declaration//GEN-END:variables
}
