/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cards;

import controller.RoteiroDeTesteController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import javax.swing.JOptionPane;
import model.RoteiroDeTestes;
import view.Paineis;
import view.mainApp;

/**
 *
 * @author matheus
 */
public class RoteiroDeTesteCard extends javax.swing.JPanel {
    
    private RoteiroDeTestes roteiroDeTestes;
    /**
     * Creates new form ProjetoCard
     */
    public RoteiroDeTesteCard(RoteiroDeTestes c) {
        initComponents();
        roteiroDeTestes = c;
        nome.setText(c.getNome());
        codigo.setText(c.getCodigo());
        Descricao.setText(c.getDescricao());
        email.setText(c.getEmailUsuario());
        iniciarListaners();
    }
    
    private void iniciarListaners(){
        btnVerEditar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HashMap<String, Object> hashMap = new HashMap<String, Object>();
                hashMap.put("roteiro", roteiroDeTestes);
                mainApp.trocarDePainel(Paineis.FORMULARIO_DE_CADASTRO_DE_ROTEIROS_DE_TESTE, hashMap);
            }
        });
        
        btnDeletar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int i = JOptionPane.showConfirmDialog(null, "Você está certo disso?", "tem certeza?", JOptionPane.YES_NO_OPTION);
                if (i == 0){
                    RoteiroDeTesteController.deletarRoteiriDeTestes(roteiroDeTestes);
                    mainApp.trocarDePainel(Paineis.ROTEIROS_DE_TESTE, null);
                }                
            }
        });
        btnExecultar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HashMap<String, Object> hashMap = new HashMap<String, Object>();
                hashMap.put("roteiro", roteiroDeTestes);
                mainApp.trocarDePainel(Paineis.EXECUCAO_DE_ROTEIRO, hashMap);
            }
        });
        btnMatriz.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HashMap<String, Object> hashMap = new HashMap<String, Object>();
                hashMap.put("roteiro", roteiroDeTestes);
                mainApp.trocarDePainel(Paineis.MATRIZ, hashMap);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        Descricao = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        btnVerEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnExecultar = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        setMaximumSize(getMinimumSize());
        setMinimumSize(new java.awt.Dimension(90, 135));

        nome.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nome.setText("nome");
        nome.setToolTipText("nome do roteiro");
        nome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        codigo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        codigo.setText("codigo");
        codigo.setToolTipText("codigo do roteiro");
        codigo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Descricao.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Descricao.setForeground(new java.awt.Color(102, 102, 102));
        Descricao.setText("descri");
        Descricao.setToolTipText("descrição do roteiro");
        Descricao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        email.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("e-mail");
        email.setToolTipText("e-mail do usuario que criou este roteiro");
        email.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnVerEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnVerEditar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnVerEditar.setForeground(new java.awt.Color(153, 153, 153));
        btnVerEditar.setText("ver/editar");
        btnVerEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnVerEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEditar.setFocusPainted(false);
        btnVerEditar.setFocusable(false);
        btnVerEditar.setOpaque(false);

        btnDeletar.setBackground(new java.awt.Color(0, 0, 0));
        btnDeletar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(153, 153, 153));
        btnDeletar.setText("deletar");
        btnDeletar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setFocusPainted(false);
        btnDeletar.setFocusable(false);
        btnDeletar.setOpaque(false);

        btnExecultar.setBackground(new java.awt.Color(0, 0, 0));
        btnExecultar.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnExecultar.setForeground(new java.awt.Color(153, 153, 153));
        btnExecultar.setText("executar");
        btnExecultar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnExecultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExecultar.setFocusPainted(false);
        btnExecultar.setFocusable(false);
        btnExecultar.setOpaque(false);

        btnMatriz.setBackground(new java.awt.Color(0, 0, 0));
        btnMatriz.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        btnMatriz.setForeground(new java.awt.Color(153, 153, 153));
        btnMatriz.setText("matriz");
        btnMatriz.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatriz.setFocusPainted(false);
        btnMatriz.setFocusable(false);
        btnMatriz.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(btnExecultar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(btnDeletar))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMatriz)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVerEditar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExecultar)
                        .addGap(5, 5, 5)
                        .addComponent(btnMatriz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigo)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerEditar)
                    .addComponent(Descricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletar)
                    .addComponent(email))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descricao;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnExecultar;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JButton btnVerEditar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
