/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cards;

/**
 *
 * @author matheus
 */
public class UsuarioCard extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioCard
     */
    public UsuarioCard(String nome, String email, String cargo) {
        initComponents();
        this.nome.setText(nome);
        this.cargo.setText(cargo);
        this.email.setText(email);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgPerfil = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        setMinimumSize(new java.awt.Dimension(0, 100));

        imgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones/imgPerfilGenerico.jpg"))); // NOI18N
        imgPerfil.setPreferredSize(new java.awt.Dimension(60, 60));

        nome.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        nome.setText("jLabel2");

        cargo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        cargo.setText("jLabel3");

        email.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        email.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargo)
                    .addComponent(email)
                    .addComponent(nome)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email)))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables

    
    
}
